### ISSUE TITLE
Running the analyzer with custom classification of the nodes

### ISSUE THREAD

**Issue by cushionbadak** [kupl/Graphick#1]
Is there any way to import custom node classification?

**Comment by MinseokJGit** [comment]
If you are in "Heap_Abstraction'', modify "CanHeap.facts'' to contain nodes that need to be analyzed precisely, where the set of nodes in "CanHeap.facts'' is a set of allocation sites.

Then, type the following:

$ ./run.py   heuristic   <pgm>

where pgm is the program to be analyzed.
