### ISSUE TITLE
There are two kinds of pmd in the paper (pmd_s, pmd_m). 

### ISSUE THREAD

**Issue by sooyoungcha** [kupl/Graphick#3]
How can we run the analyzer with pmd_s and pmd_m?

**Comment by MinseokJGit** [comment]
pmd_m corresponds to pmdm and pmd_s corresponds to pmd.

If you want to run the analyzer with pmd_s, type:
$./run.py graphick pmd

If you want to run the analyzer with pmd_m, type:
$./run.py graphick pmdm
