### ISSUE TITLE
error: predicate 'HeapAllocationRef' is not declared at level 0 (code: PREDICATE_UNDECLARED)

### ISSUE THREAD

**Issue by LuoRongLuoRong** [kupl/Graphick#6]
I ran the project and got lots of errors:

![image](https://user-images.githubusercontent.com/37246260/173876312-ef665c4b-df56-41c7-87a3-31ec21a7e87e.png)

I have no idea. Could you please tell me the reason and solution?

**Comment by MinseokJGit** [comment]
I think the cached database used has a problem (e.g., .../Graphick/Ctx_sensitivity/doop/**cache**/...):

![image](https://user-images.githubusercontent.com/17019014/173982979-fce1f2ee-7fa3-4550-bab5-71366827f4a0.png)

Please, clear the cache database before the analysis by typing the following command:

 $ rm -r /home/fdse/luorong/course/Graphick/Ctx_Sensitivity/doop/cache/*

Then, run the analysis:

$ ./run.py graphick luindex

I will reproduce a result in our paper:

<img width="1099" alt="image" src="https://user-images.githubusercontent.com/17019014/173983358-44f6033e-9333-4410-8af3-4d50c9726676.png">

**Comment by MinseokJGit** [comment]
Hi @LuoRongLuoRong, if you find the answer satisfactory, please close the issue. Otherwise, if there is another question, feel free to leave it here.

**Comment by LuoRongLuoRong** [comment]
Thanks!
